version: "3.8"

services:
  postgresql:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
      start_interval: 10s
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRESS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
    volumes:
      - product_data:/var/lib/postgresql/12.22/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - backend_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/api/check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
      start_interval: 10s
    env_files: ./backend/.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - backend_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
  
networks:
  backend_network:
    driver: bridge

volumes:
  product_data: