version: "3.8"

services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
      start_interval: 10s
    volumes:
      - payment_data:/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - bokman_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1024M"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/api/check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
      start_interval: 10s
    env_file: ./backend/.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - bokman_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

networks:
  bokman_network:
    external: true
  
volumes:
  payment_data: