const express = require('express');
import { getFirestore, collection, getDocs, Timestamp } from 'firebase/firestore/lite';
import { initializeApp } from "firebase/app";
require('dotenv').config();

const app = express();
app.use(express.json());

const firebaseConfig = {
    apiKey: "AIzaSyB8Zyr0l80dExVV0fl1iCYN3-1iqnVY0Dc",
    authDomain: "microservice-ci-cd.firebaseapp.com",
    projectId: "microservice-ci-cd",
    storageBucket: "microservice-ci-cd.firebasestorage.app",
    messagingSenderId: "158367224073",
    appId: "1:158367224073:web:82c2329638d11db06203d8",
    measurementId: "G-VV6ZHFL43Z"
};

// Firestore Connection
const firebase = initializeApp(firebaseConfig);
const db = getFirestore(firebase);

app.get('/api/check', async( req, res ) => {
    return res.status(200).json({ message: "ok" })
})

// Add notification
app.post('/notifications', async (req, res) => {
    const { user_id, message } = req.body;
    
    try {
        // Reference to 'bokman' collection
        const bokmanCol = collection(db, 'bokman');
        
        // Create a new document with data
        const newNotification = {
            user_id,
            message,
            createdAt: Timestamp.fromDate(new Date()),  // Store the current date and time
            id: Math.random().toString(36).substr(2, 9) // Generate a random ID for the notification
        };
        
        // Add the new notification to the 'bokman' collection
        const docRef = await addDoc(bokmanCol, newNotification);

        // Respond with the document reference (including the ID generated by Firestore)
        return res.status(201).json({
            id: docRef.id,
            ...newNotification
        });
    } catch (err) {
        console.log(err);
        return res.status(500).json({ error: err.message });
    }
});

// Get notification by ID
app.get('/notifications/:id', async (req, res) => {
    const { id } = req.params;
    try {
        const bokmanCol = collection( db, 'bokman' )
        const q = query(bokmanCol, where('id', '==', id));  // Query for documents where 'id' matches the parameter
        const bokmanSnapshot = await getDocs(q);  // Get documents matching the query
        
        if (bokmanSnapshot.empty) {
            // If no documents are found, return 404
            return res.status(404).json({ error: 'Notification not found' });
        }

        // Map the documents to extract their data
        const notificationList = bokmanSnapshot.docs.map(doc => doc.data());
        return res.status(200).json(notificationList);  // Return the matching documents

    }

    catch( err ) {
        console.log( err )
        return res.status(500).json({ err })
    }
});

app.listen(3005, () => console.log('Notification Service running on port 3005'));
