version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile 
  healthcheck:
    test: ["CMD", "curl", "-f", "-H", "Content-Type: application/json", "http://localhost:${BACKEND_PORT}/api/check"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 20s
    start_interval: 10s
  env_file: ./backend/.env
  ports:
    - "${BACKEND_PORT}:${BACKEND_PORT}"
  networks:
    - bokman_network
  logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  deploy:
    resources:
      limits:
        cpus: "0.5"
        memory: "512M"

networks:
  bokman_network:
    external: true