version: "3.8"

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
      start_interval: 10s
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - user_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - bokman_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "Content-Type: application/json", "http://localhost:${BACKEND_PORT}/api/check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
      start_interval: 10s
    env_file: ./backend/.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - bokman_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

networks:
  bokman_network:
    external: true

volumes:
  user_data: