name: Product service workflow

run-name: Deploy product service to server by ${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'services/product-service/**'

jobs:
  build:
    runs-on: self-hosted
  
    steps:
      - name: Disable the product-service containers
        run: | 
          echo "Stopping product-service containers"
          docker compose down || { echo "Failed to stop containers"; exit 1; }
        working-directory: ${{ secrets.PRODUCT_SERVICE_DIRECTORY }}

      - name: Pull the latest change for product-service
        run: |
            echo "Pulling latest changes for product-service..."
            git pull origin main || { echo "Failed to pull latest changes"; exit 1; }
        working-directory: ${{ secrets.PROJECT_ROOT_DIRECTORY }}
      
      - name: Run the user-service docker-compose file
        run: |
          echo "Build and run the containers" 
          docker compose up -d --build || { echo "Failed to run the container"; exit 1; }
        working-directory: ${{ secrets.PRODUCT_SERVICE_DIRECTORY }}

