name: User service workflow

run-name: Deploy user service to server by ${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'services/user-service/**'

jobs:
  build:
    runs-on: ${{ secrets.RUNS_ON }}
  
    steps:
      - name: Disable the user-service containers
        run: | 
          echo "Stopping user-service containers"
          docker compose down || { echo "Failed to stop containers"; exit 1; }
        working-directory: ${{ secrets.USER_SERVICE_DIRECTORY}}

      - name: Pull the latest change for user-service
        run: |
            echo "Pulling latest changes for user-service..."
            git pull origin main || { echo "Failed to pull latest changes"; exit 1; }
        working-directory: ${{ secrets.PROJECT_ROOT_DIRECTORY }}
      
      - name: Run the user-service docker-compose file
        run: |
          echo "Build and run the containers" 
          docker compose up -d --build || { echo "Failed to run the container"; exit 1; }
        working-directory: ${{ secrets.USER_SERVICE_DIRECTORY }}

